item {
    id: 1
    name: 'plava_patkica'
}
item {
    id: 2
    name: 'CASIO_fx_991ES'
}
item {
    id: 3
    name: 'CASIO_fx_991ES_PLUS'
}
item {
    id: 4
    name: 'foi_gujdica'
}
item {
    id: 5
    name: 'strumf'
}